# Generated by Django 5.1.7 on 2025-03-15 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoCanalServicio', models.CharField(max_length=5)),
                ('nombreCanalServicio', models.CharField(max_length=100)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('fechaModificado', models.DateTimeField(auto_now=True)),
                ('idUsuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoTipoCliente', models.CharField(max_length=5)),
                ('nombreTipoCliente', models.CharField(max_length=100)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('fechaModificado', models.DateTimeField(auto_now=True)),
                ('idUsuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoTipoMovimiento', models.CharField(max_length=2)),
                ('codigoTipoTransaccion', models.IntegerField()),
                ('nombreTipoTransaccion', models.CharField(max_length=100)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField(auto_now=True)),
                ('idUsuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoUsuario', models.CharField(max_length=40)),
                ('nombreUsuario', models.CharField(max_length=100)),
                ('passwordUsuario', models.CharField(max_length=80)),
                ('isActivo', models.BooleanField(default=True)),
                ('ultimaConexion', models.DateTimeField(auto_now=True)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('fechaModificado', models.DateTimeField(auto_now=True)),
                ('idUsuarioRegistro', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Agencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoAgencia', models.CharField(max_length=6)),
                ('nombreAgencia', models.CharField(max_length=100)),
                ('direccionAgencia', models.CharField(max_length=255)),
                ('telefonoAgencia', models.CharField(max_length=20)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('fechaModificado', models.DateTimeField(auto_now=True)),
                ('idUsuario', models.IntegerField()),
                ('idCanalServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.canalservicio')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoCliente', models.CharField(max_length=20)),
                ('numeroIdentidad', models.CharField(max_length=40)),
                ('nombreCliente', models.CharField(max_length=100)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('fechaModificado', models.DateTimeField(auto_now=True)),
                ('idUsuario', models.IntegerField()),
                ('idTipoCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipocliente')),
            ],
        ),
        migrations.CreateModel(
            name='MotivoTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoMotivoTransaccion', models.CharField(max_length=5)),
                ('nombreMotivoTransaccion', models.CharField(max_length=100)),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('fechaModificado', models.DateTimeField(auto_now=True)),
                ('idUsuario', models.IntegerField()),
                ('idTipoTransaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipotransaccion')),
            ],
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaTransaccion', models.DateTimeField(auto_now_add=True)),
                ('montoTransaccion', models.DecimalField(decimal_places=4, max_digits=12)),
                ('idUsuario', models.IntegerField()),
                ('idAgencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agencias')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
                ('idMotivoTransaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.motivotransaccion')),
            ],
        ),
    ]
