# Generated by Django 5.1.7 on 2025-03-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usuarios_groups_usuarios_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='codigoUsuario',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombreUsuario',
            field=models.CharField(max_length=100),
        ),
    ]
