# Generated by Django 5.1.7 on 2025-03-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_usuarios_groups_remove_usuarios_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='codigoUsuario',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombreUsuario',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
