# Generated by Django 5.1.7 on 2025-03-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_registroacciones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroAcciones',
        ),
    ]
