# Generated by Django 5.1.7 on 2025-03-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_registroacciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=100)),
                ('accion', models.CharField(choices=[('LogIn', 'LogIn'), ('LogOut', 'LogOut')], max_length=10)),
                ('fechaHora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
